services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www-astro-builder
    volumes:
      # Repositorio (fuente)
      - /home/debian/github/www-astro:/app
      # Directorios de Apache (destino del build)
      - /home/debian/prueba-astro/blog_pledin/html/pledin:/dist/www
      - /home/debian/prueba-astro/plataforma_pledin/html/pledin:/dist/plataforma
      - /home/debian/prueba-astro/fp_pledin/html:/dist/fp
    restart: unless-stopped
